Add language prompt on first login
NyalaDev/edu-ui pull request #38
Opened 2021-03-10 18:54 UTC by alaa-yahia

![image](https://user-images.githubusercontent.com/6881345/110681674-bdb0ba80-81e2-11eb-8c36-75d7fed76c42.png)

2021-03-11 04:00 UTC, abolkog requested changes
Thanks Alaa, just minor CSS tweaks for mobile layouts.

2021-03-11 08:59 UTC, abolkog approved these changes
All good @alaa-yahia , can you please resolve the conflict and we are good to merge

2021-03-11 15:14 UTC, kabaros requested changes
@alaa-yahia I added Swahili to the languages, please add it to `const.js` (also rename that file to constants.js please) .. 

Also add any new resources to the local files to all four languages, at the end of the file so that it's easier to find ... for Amharic and Swahili, just add the English text in the resource until we ask someone to translate (add a comment before them `Todo: Translate these keys`)

2021-03-13 12:16 UTC, kabaros approved these changes

2021-03-13 12:17 UTC, merged